### ISSUE TITLE
Rendering of seperate tables as html files

### ISSUE THREAD

**Issue by IanSudbery** [AndreasHeger/CGATReport#10]
I have a tracker that renders tables beyond the length at which tables are inserted in the report page.
The tracker works via cgatreport-test, but when included in a page gives the following error:
```python-traceback
CGATReportError

    stage: collection

    exception: IOError

    message: [Errno 2] No such file or directory: \u2018_static/report_directive/Motifs_DREMELocations@table@f723a5d056535c5ec0c0a9e7d7141e20_Alyref-FLAG-R3/GMAS.html\u2019

    traceback:

        File \u201c/ifs/devel/Ian/python/lib/python2.7/site-packages/CGATReport-0.2.1-py2.7.egg/CGATReport/report_directive.py\u201d, line 370, in run

            links=links))
        File \u201c/ifs/devel/Ian/python/lib/python2.7/site-packages/CGATReport-0.2.1-py2.7.egg/CGATReportPlugins/HTMLPlugin/__init__.py\u201d, line 49, in collect

            outf = open(outputpath, \u201cw\u201d)

```

I assume this is because the track/slice using '/' as the separator is being interpreted as a directory: the render will fail to save the file because the directory won't exist.  

Ian
----

**Comment by AndreasHeger** [comment]
@IanSudbery

Yes, that might be the problem. I will need to change the "separator" inside the paths of the datatree.
