### ISSUE TITLE
Dataframe shape when using getValues

### ISSUE THREAD

**Issue by IanSudbery** [AndreasHeger/CGATReport#13]
If I have a tracker that returns a list of values, via self.getValues, I usually get a DataFrame with a multi-level index (track, slice) and a single column. This can then be passed by track or by slice to various down stream transforms or renders. However, if by any chance all the track, slice combinations have the same length (e.g. I have one track and two slices, and each slice returns 100 values) then I get a DataFrame with a single level index (track) and a column for each slice. 

This makes it very difficult to know what sort of dataframe my tracker is going to return, sometimes its a multi-indexed series and sometimes a multi-columned dataframe, and there is no way of telling which will be returned.

**Comment by AndreasHeger** [comment]
Hi @IanSudbery,

the conversion between data trees and data frames makes the assumption that if all arrays have the same length they are treated as coordinate data. This was necessary to not break the majority of plotters.

I will think of a solution.
 Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Hi @IanSudbery, I have had a bit of a think. Unfortunately there is no quick work-around. The only principle solution is to return all data fully "melted", which will break a lot of things.

Workarounds in your case could be:
1. use :transform: melt
2. do not use getValues, but getDataFrame()

Is this ok?
Best, Andreas
