### ISSUE TITLE
Missing templates

### ISSUE THREAD

**Issue by niejen** [AndreasHeger/CGATReport#21]
The templates are missing from my version:
(copied by typing, running in VM...)

```
cgatreport-quickstart -d newproject
.....
IOerror: [Errno 2] No such file .... /templates/Makefile
```

The whole CGATReport/templates directory is missing.
I was trying to install on Debian/testing.
I installed most of the required packages through apt-get, then "pip install cgatreport".
I end with an empty Makefile in the newproject directory.

**Comment by AndreasHeger** [comment]
Hi, I have just released a new version, can you try giving it a go?

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Closing for now.
