### ISSUE TITLE
table renders  have no ouput when large

### ISSUE THREAD

**Issue by IanSudbery** [AndreasHeger/CGATReport#37]
I don't know when this started happening, but table renders above the max_rows are not outputting the linked html or xls, and the outputted rst is missing the anchor to the external file:

e.g.:

```
$ cat "_static/report_directive/RetainedIntrons_DetainedChunkSplicing@table@289a80e716c61fbbc9fb0060fb515621.txt"
`803205 x 12 table <#$html $#>`__




::
```

**Comment by AndreasHeger** [comment]
Thanks, will take a look.

**Comment by IanSudbery** [comment]
Cheers. 

Now `gallery-plot` is doing something I can only assume is the same. 

![image](https://user-images.githubusercontent.com/5391758/29568719-264ed51a-8749-11e7-99c3-f871394b69fe.png)

**Comment by IanSudbery** [comment]
Okay. I think that was something different. See #38

**Comment by AndreasHeger** [comment]
Hi Ian, should be fixed now. The issue was that now Display elements are collected during Rendering to reduce memory foot-print. This is generic functionality, but the Table Renderer had its own __call__ method where this was not implemented.
