### ISSUE TITLE
Column ordering/returning dataframes

### ISSUE THREAD

**Issue by IanSudbery** [AndreasHeger/CGATReport#9]
In sphinx report v1, returning and odict of odicts would result in a table with row and column order preserved. 

However, since the move to dataframes, the conversion of the odict of odicts to Dataframe causes the loss of column order.

One solution to this is to build the result directly as a dataframe in the tracker like so:

```python

result = pandas.DataFrame(columns=["col1","col2","col3"])

for line in data:
    result.append(odict(("col1", do_stuff1(line[1])),
                        ("col2", line[2].some_attribute),
                        ("col3", line[3] + line[0]), ignore_index=True)

return result
```

However, if for some track, `data` is empty, then an empy dataframe is returned and you get this error:

```python-traceback
raceback (most recent call last):
  File "/ifs/devel/Ian/python/bin/cgatreport-test", line 9, in <module>
    load_entry_point('CGATReport==0.2.1', 'console_scripts', 'cgatreport-test')()
  File "/ifs/devel/Ian/python/lib/python2.7/site-packages/CGATReport-0.2.1-py2.7.egg/CGATReport/test.py", line 488, in main
    result = dispatcher(**kwargs)
  File "/ifs/devel/Ian/python/lib/python2.7/site-packages/CGATReport-0.2.1-py2.7.egg/CGATReport/Dispatcher.py", line 645, in __call__
    self.data = DataTree.asDataFrame(self.tree)
  File "/ifs/devel/Ian/python/lib/python2.7/site-packages/CGATReport-0.2.1-py2.7.egg/CGATReport/DataTree.py", line 421, in asDataFrame
    assert min(levels) == max(levels)
AssertionError
```

This can be solved by changing `return result` to

```python
if result.shape[0] > 0:
    return result
```

But this seems awefully clunky. Is there a better way? Can the conversion from odict to DataFrame be rewritten to preserve column order?

**Comment by AndreasHeger** [comment]
@IanSudbery, thanks. The column order is preserved to same extent (see DataTree.asDataframe()).
The problem is that the pandas concat method will sort the columns lexicographically if they are
not identical in all dataframes. There is already a fix to remove empty dataframes (triggers a sort).

See also DataTree for a solution:
```python

        column_set = collections.OrderedDict()
        for d in dataframes:
            column_set.update(collections.OrderedDict(
                [(x, 0) for x in d.columns]))

        df = df.reindex_axis(column_set.keys(), axis=1)
```

**Comment by AndreasHeger** [comment]
I will see if this re-sorting can be enabled for all conversions.

**Comment by IanSudbery** [comment]
Thanks

**Comment by AndreasHeger** [comment]
Should work now - please give it a go.
